GET http://localhost:5162/games

###
GET http://localhost:5162/games/4

###
POST http://localhost:5162/games
Content-Type: application/json

{
  "name": "Super Mario Bros",
  "genre": "Platformer",
  "price": 59.99,
  "releaseDate": "1985-09-13"
}